### ISSUE TITLE
Add link to Cambridge Solar map

### ISSUE THREAD

**Issue by cambridgegis** [cambridgegis/AddressDashboard#8]
CDD has requested a link to the solar map but we need a way to permalink to a building (or address) on their end.  Right now the permalinks on their site are created using their building ID (which is not the same as ours).  See here for an example:

http://en.mapdwell.com/solarsystem/cambridge?bid=12720

**Comment by seansweeney** [comment]
Mapdwell created their own building IDs and have refused to work with us to create a mapping, so this link is not possible for us to do reasonably.
